# Generated by Django 4.2.3 on 2023-07-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=150, verbose_name='Assunto')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services', verbose_name='Imagem')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('image', models.ImageField(blank=True, null=True, upload_to='skills', verbose_name='Imagem')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Porcentagem')),
                ('level', models.IntegerField(verbose_name='Nível')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('icons', models.CharField(max_length=100, verbose_name='Ícone')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects', verbose_name='Imagem')),
                ('url_project', models.URLField(blank=True, null=True, verbose_name='URL Project')),
                ('url_github', models.URLField(blank=True, null=True, verbose_name='URL Github')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('tags', models.ManyToManyField(to='portfolio.tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('image', models.ImageField(blank=True, null=True, upload_to='aboutme', verbose_name='Imagem')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address', models.CharField(max_length=200, verbose_name='Endereço')),
                ('phone', models.CharField(max_length=14, verbose_name='Telefone')),
                ('url_site', models.URLField(blank=True, null=True, verbose_name='URL Site')),
                ('url_linkedin', models.URLField(blank=True, null=True, verbose_name='URL Linkedin')),
                ('url_github', models.URLField(blank=True, null=True, verbose_name='URL Github')),
                ('url_instagram', models.URLField(blank=True, null=True, verbose_name='URL Instagram')),
                ('url_facebook', models.URLField(blank=True, null=True, verbose_name='URL Facebook')),
                ('url_twitter', models.URLField(blank=True, null=True, verbose_name='URL Twitter')),
                ('url_youtube', models.URLField(blank=True, null=True, verbose_name='URL Youtube')),
                ('url_whatsapp', models.CharField(blank=True, max_length=20, null=True, verbose_name='URL Whatsapp')),
                ('url_telegram', models.CharField(blank=True, max_length=20, null=True, verbose_name='URL Telegram')),
                ('skills', models.ManyToManyField(to='portfolio.skill', verbose_name='Skills')),
            ],
            options={
                'verbose_name': 'Sobre mim',
                'verbose_name_plural': 'Sobre mim',
            },
        ),
    ]
