# Generated by Django 4.2.3 on 2023-07-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_aboutme_skills_alter_project_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='skills',
            field=models.ManyToManyField(blank=True, to='portfolio.skill', verbose_name='Skills'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, to='portfolio.tag', verbose_name='Tags'),
        ),
    ]
