# Generated by Django 4.2.3 on 2023-07-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_contact_active_contact_progress_contact_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.CharField(choices=[('B', 'Básico'), ('I', 'Intermediário'), ('A', 'Avançado'), ('E', 'Expert')], default='B', max_length=1, verbose_name='Nível'),
        ),
    ]
