# Generated by Django 4.2.3 on 2023-07-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_contact_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='progress',
            field=models.IntegerField(choices=[(0, 'Não iniciado'), (1, 'Em andamento'), (2, 'Finalizado')], default=0, verbose_name='Progresso'),
        ),
    ]
